apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: laptop
  name: laptop
spec:
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: laptop
status:
  loadBalancer: {}
